// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureQuotaRow = `-- name: EnsureQuotaRow :exec
INSERT INTO ai_usage_quota (school_id, academic_year_id, month, generations_used, generations_limit)
VALUES ($1, $2, $3, 0, 500)
ON CONFLICT (school_id, month) DO NOTHING
`

type EnsureQuotaRowParams struct {
	SchoolID       pgtype.UUID `json:"school_id"`
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
	Month          pgtype.Date `json:"month"`
}

// Creates the school's quota row for a month if absent; no-op otherwise.
func (q *Queries) EnsureQuotaRow(ctx context.Context, arg EnsureQuotaRowParams) error {
	_, err := q.db.Exec(ctx, ensureQuotaRow, arg.SchoolID, arg.AcademicYearID, arg.Month)
	return err
}

const getCachedGeneration = `-- name: GetCachedGeneration :one
SELECT id, school_id, teacher_id, feature, prompt_version, input_hash, input_json, output_json, language, model, cost_inr, generated_at, cache_expires_at FROM ai_generations
WHERE school_id = $1 AND input_hash = $2 AND feature = $3
  AND cache_expires_at > now()
ORDER BY generated_at DESC
LIMIT 1
`

type GetCachedGenerationParams struct {
	SchoolID  pgtype.UUID `json:"school_id"`
	InputHash string      `json:"input_hash"`
	Feature   string      `json:"feature"`
}

// 30-day cache lookup by normalized input hash — a hit must be
// near-instant and must not call Claude or consume quota (F-05).
func (q *Queries) GetCachedGeneration(ctx context.Context, arg GetCachedGenerationParams) (AiGeneration, error) {
	row := q.db.QueryRow(ctx, getCachedGeneration, arg.SchoolID, arg.InputHash, arg.Feature)
	var i AiGeneration
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.Feature,
		&i.PromptVersion,
		&i.InputHash,
		&i.InputJson,
		&i.OutputJson,
		&i.Language,
		&i.Model,
		&i.CostInr,
		&i.GeneratedAt,
		&i.CacheExpiresAt,
	)
	return i, err
}

const getCurrentAcademicYear = `-- name: GetCurrentAcademicYear :one
SELECT id FROM academic_years
WHERE school_id = $1 AND is_current
LIMIT 1
`

func (q *Queries) GetCurrentAcademicYear(ctx context.Context, schoolID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCurrentAcademicYear, schoolID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getQuota = `-- name: GetQuota :one
SELECT generations_used, generations_limit FROM ai_usage_quota
WHERE school_id = $1 AND month = $2
`

type GetQuotaParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Month    pgtype.Date `json:"month"`
}

type GetQuotaRow struct {
	GenerationsUsed  int32 `json:"generations_used"`
	GenerationsLimit int32 `json:"generations_limit"`
}

func (q *Queries) GetQuota(ctx context.Context, arg GetQuotaParams) (GetQuotaRow, error) {
	row := q.db.QueryRow(ctx, getQuota, arg.SchoolID, arg.Month)
	var i GetQuotaRow
	err := row.Scan(&i.GenerationsUsed, &i.GenerationsLimit)
	return i, err
}

const insertGeneration = `-- name: InsertGeneration :one
INSERT INTO ai_generations (
    school_id, teacher_id, feature, prompt_version, input_hash,
    input_json, output_json, language, model, cost_inr, cache_expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now() + interval '30 days')
RETURNING id, school_id, teacher_id, feature, prompt_version, input_hash, input_json, output_json, language, model, cost_inr, generated_at, cache_expires_at
`

type InsertGenerationParams struct {
	SchoolID      pgtype.UUID    `json:"school_id"`
	TeacherID     pgtype.UUID    `json:"teacher_id"`
	Feature       string         `json:"feature"`
	PromptVersion string         `json:"prompt_version"`
	InputHash     string         `json:"input_hash"`
	InputJson     []byte         `json:"input_json"`
	OutputJson    []byte         `json:"output_json"`
	Language      string         `json:"language"`
	Model         string         `json:"model"`
	CostInr       pgtype.Numeric `json:"cost_inr"`
}

func (q *Queries) InsertGeneration(ctx context.Context, arg InsertGenerationParams) (AiGeneration, error) {
	row := q.db.QueryRow(ctx, insertGeneration,
		arg.SchoolID,
		arg.TeacherID,
		arg.Feature,
		arg.PromptVersion,
		arg.InputHash,
		arg.InputJson,
		arg.OutputJson,
		arg.Language,
		arg.Model,
		arg.CostInr,
	)
	var i AiGeneration
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.Feature,
		&i.PromptVersion,
		&i.InputHash,
		&i.InputJson,
		&i.OutputJson,
		&i.Language,
		&i.Model,
		&i.CostInr,
		&i.GeneratedAt,
		&i.CacheExpiresAt,
	)
	return i, err
}

const releaseQuota = `-- name: ReleaseQuota :exec
UPDATE ai_usage_quota
SET generations_used = GREATEST(generations_used - $3, 0)
WHERE school_id = $1 AND month = $2
`

type ReleaseQuotaParams struct {
	SchoolID        pgtype.UUID `json:"school_id"`
	Month           pgtype.Date `json:"month"`
	GenerationsUsed int32       `json:"generations_used"`
}

// Returns reserved quota after a failed Claude call — reservation
// happens before the call (F-05: "checked before calling Claude"), so a
// failure must give the generation back.
func (q *Queries) ReleaseQuota(ctx context.Context, arg ReleaseQuotaParams) error {
	_, err := q.db.Exec(ctx, releaseQuota, arg.SchoolID, arg.Month, arg.GenerationsUsed)
	return err
}

const reserveQuota = `-- name: ReserveQuota :one
UPDATE ai_usage_quota
SET generations_used = generations_used + $3
WHERE school_id = $1 AND month = $2
  AND generations_used + $3 <= generations_limit
RETURNING generations_limit - generations_used AS remaining
`

type ReserveQuotaParams struct {
	SchoolID        pgtype.UUID `json:"school_id"`
	Month           pgtype.Date `json:"month"`
	GenerationsUsed int32       `json:"generations_used"`
}

// Atomically consumes $3 generations if (and only if) the whole amount
// fits under the limit — partial batch reservations are all-or-nothing
// per F-09 ("warn before starting a batch that would exceed the
// remaining quota, don't fail partway through").
func (q *Queries) ReserveQuota(ctx context.Context, arg ReserveQuotaParams) (int32, error) {
	row := q.db.QueryRow(ctx, reserveQuota, arg.SchoolID, arg.Month, arg.GenerationsUsed)
	var remaining int32
	err := row.Scan(&remaining)
	return remaining, err
}

const updateGenerationOutput = `-- name: UpdateGenerationOutput :one
UPDATE ai_generations
SET output_json = $3
WHERE id = $1 AND teacher_id = $2
RETURNING id
`

type UpdateGenerationOutputParams struct {
	ID         pgtype.UUID `json:"id"`
	TeacherID  pgtype.UUID `json:"teacher_id"`
	OutputJson []byte      `json:"output_json"`
}

// Saves a teacher's inline edits. Scoped to the owning teacher — RLS
// already scopes to the school, this narrows to the author.
func (q *Queries) UpdateGenerationOutput(ctx context.Context, arg UpdateGenerationOutputParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateGenerationOutput, arg.ID, arg.TeacherID, arg.OutputJson)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
