// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAttendanceHistory = `-- name: GetAttendanceHistory :many
SELECT ar.student_id, s.full_name, ar.date, ar.status
FROM attendance_records ar
JOIN students s ON s.id = ar.student_id
WHERE ar.section_id = $1 AND ar.date BETWEEN $2 AND $3
ORDER BY ar.date, s.full_name
`

type GetAttendanceHistoryParams struct {
	SectionID pgtype.UUID `json:"section_id"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
}

type GetAttendanceHistoryRow struct {
	StudentID pgtype.UUID `json:"student_id"`
	FullName  string      `json:"full_name"`
	Date      pgtype.Date `json:"date"`
	Status    string      `json:"status"`
}

// Backs GET /api/:school/attendance/history?section_id=&from=&to=.
func (q *Queries) GetAttendanceHistory(ctx context.Context, arg GetAttendanceHistoryParams) ([]GetAttendanceHistoryRow, error) {
	rows, err := q.db.Query(ctx, getAttendanceHistory, arg.SectionID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceHistoryRow
	for rows.Next() {
		var i GetAttendanceHistoryRow
		if err := rows.Scan(
			&i.StudentID,
			&i.FullName,
			&i.Date,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlaggedStudents = `-- name: GetFlaggedStudents :many
WITH recent AS (
    SELECT
        student_id,
        date,
        status,
        ROW_NUMBER() OVER (PARTITION BY student_id ORDER BY date DESC) AS rn
    FROM attendance_records
    WHERE school_id = $1 AND date <= CURRENT_DATE
)
SELECT student_id, COUNT(*) AS consecutive_absences
FROM recent
WHERE rn <= 3 AND status = 'absent'
GROUP BY student_id
HAVING COUNT(*) = 3
`

type GetFlaggedStudentsRow struct {
	StudentID           pgtype.UUID `json:"student_id"`
	ConsecutiveAbsences int64       `json:"consecutive_absences"`
}

// Students with 3+ consecutive absences ending today, computed on read
// per the Database Schema document's "derived logic, not stored" note.
func (q *Queries) GetFlaggedStudents(ctx context.Context, schoolID pgtype.UUID) ([]GetFlaggedStudentsRow, error) {
	rows, err := q.db.Query(ctx, getFlaggedStudents, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlaggedStudentsRow
	for rows.Next() {
		var i GetFlaggedStudentsRow
		if err := rows.Scan(&i.StudentID, &i.ConsecutiveAbsences); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchoolAttendanceSummary = `-- name: GetSchoolAttendanceSummary :one
SELECT
    COUNT(*) FILTER (WHERE status = 'present') AS present_count,
    COUNT(*) AS total_count
FROM attendance_records
WHERE school_id = $1 AND date = $2
`

type GetSchoolAttendanceSummaryParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Date     pgtype.Date `json:"date"`
}

type GetSchoolAttendanceSummaryRow struct {
	PresentCount int64 `json:"present_count"`
	TotalCount   int64 `json:"total_count"`
}

// School-wide attendance percentage for a given date — a single
// indexed aggregate, cheap enough to compute live rather than cache,
// per the Database Schema document.
func (q *Queries) GetSchoolAttendanceSummary(ctx context.Context, arg GetSchoolAttendanceSummaryParams) (GetSchoolAttendanceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSchoolAttendanceSummary, arg.SchoolID, arg.Date)
	var i GetSchoolAttendanceSummaryRow
	err := row.Scan(&i.PresentCount, &i.TotalCount)
	return i, err
}

const getTodayAttendance = `-- name: GetTodayAttendance :many
SELECT
    s.id AS student_id,
    s.full_name,
    ar.status
FROM students s
LEFT JOIN attendance_records ar
    ON ar.student_id = s.id AND ar.date = $2
WHERE s.section_id = $1 AND s.is_active = true
ORDER BY s.full_name
`

type GetTodayAttendanceParams struct {
	SectionID pgtype.UUID `json:"section_id"`
	Date      pgtype.Date `json:"date"`
}

type GetTodayAttendanceRow struct {
	StudentID pgtype.UUID `json:"student_id"`
	FullName  string      `json:"full_name"`
	Status    *string     `json:"status"`
}

// Backs GET /api/:school/attendance/today — returns every student in a
// section with their attendance status for a given date, if marked.
func (q *Queries) GetTodayAttendance(ctx context.Context, arg GetTodayAttendanceParams) ([]GetTodayAttendanceRow, error) {
	rows, err := q.db.Query(ctx, getTodayAttendance, arg.SectionID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTodayAttendanceRow
	for rows.Next() {
		var i GetTodayAttendanceRow
		if err := rows.Scan(&i.StudentID, &i.FullName, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttendanceStatus = `-- name: UpdateAttendanceStatus :one
UPDATE attendance_records
SET status = $2, edited_at = now(), edited_by = $3
WHERE id = $1 AND date = $4
RETURNING id
`

type UpdateAttendanceStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	EditedBy pgtype.UUID `json:"edited_by"`
	Date     pgtype.Date `json:"date"`
}

// Backs PATCH /api/:school/attendance/:id. The date predicate enforces
// the same-school-day-only edit rule (F-02) at the query level as well
// as in the handler — an id from a past day matches zero rows.
func (q *Queries) UpdateAttendanceStatus(ctx context.Context, arg UpdateAttendanceStatusParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateAttendanceStatus,
		arg.ID,
		arg.Status,
		arg.EditedBy,
		arg.Date,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertAttendance = `-- name: UpsertAttendance :one
INSERT INTO attendance_records (school_id, student_id, section_id, date, status, marked_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (student_id, date)
DO UPDATE SET
    status     = EXCLUDED.status,
    edited_at  = now(),
    edited_by  = EXCLUDED.marked_by
RETURNING id, school_id, student_id, section_id, date, status, marked_by, marked_at, edited_at, edited_by
`

type UpsertAttendanceParams struct {
	SchoolID  pgtype.UUID `json:"school_id"`
	StudentID pgtype.UUID `json:"student_id"`
	SectionID pgtype.UUID `json:"section_id"`
	Date      pgtype.Date `json:"date"`
	Status    string      `json:"status"`
	MarkedBy  pgtype.UUID `json:"marked_by"`
}

// Upserts a single student's attendance for a date, matching the
// unique(student_id, date) constraint. Called once per student in a
// loop from the submitAttendance handler — see API Specification,
// Section 03.
func (q *Queries) UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, upsertAttendance,
		arg.SchoolID,
		arg.StudentID,
		arg.SectionID,
		arg.Date,
		arg.Status,
		arg.MarkedBy,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.StudentID,
		&i.SectionID,
		&i.Date,
		&i.Status,
		&i.MarkedBy,
		&i.MarkedAt,
		&i.EditedAt,
		&i.EditedBy,
	)
	return i, err
}
