// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: communication.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPTMSlot = `-- name: CreatePTMSlot :one
INSERT INTO ptm_slots (school_id, teacher_id, slot_time)
VALUES ($1, $2, $3)
RETURNING id, school_id, teacher_id, slot_time, is_booked, created_at
`

type CreatePTMSlotParams struct {
	SchoolID  pgtype.UUID        `json:"school_id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	SlotTime  pgtype.Timestamptz `json:"slot_time"`
}

func (q *Queries) CreatePTMSlot(ctx context.Context, arg CreatePTMSlotParams) (PtmSlot, error) {
	row := q.db.QueryRow(ctx, createPTMSlot, arg.SchoolID, arg.TeacherID, arg.SlotTime)
	var i PtmSlot
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.SlotTime,
		&i.IsBooked,
		&i.CreatedAt,
	)
	return i, err
}

const getBroadcastRecipients = `-- name: GetBroadcastRecipients :many
SELECT g.id AS guardian_id, g.student_id, g.language_pref
FROM guardians g
JOIN students s ON s.id = g.student_id
WHERE s.school_id = $1 AND s.is_active AND g.is_primary_contact
  AND ($2::uuid IS NULL OR s.section_id = $2)
ORDER BY g.student_id
`

type GetBroadcastRecipientsParams struct {
	SchoolID  pgtype.UUID `json:"school_id"`
	SectionID pgtype.UUID `json:"section_id"`
}

type GetBroadcastRecipientsRow struct {
	GuardianID   pgtype.UUID `json:"guardian_id"`
	StudentID    pgtype.UUID `json:"student_id"`
	LanguagePref string      `json:"language_pref"`
}

// Primary guardians of active students, optionally narrowed to a section.
func (q *Queries) GetBroadcastRecipients(ctx context.Context, arg GetBroadcastRecipientsParams) ([]GetBroadcastRecipientsRow, error) {
	rows, err := q.db.Query(ctx, getBroadcastRecipients, arg.SchoolID, arg.SectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBroadcastRecipientsRow
	for rows.Next() {
		var i GetBroadcastRecipientsRow
		if err := rows.Scan(&i.GuardianID, &i.StudentID, &i.LanguagePref); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentWithPrimaryGuardian = `-- name: GetStudentWithPrimaryGuardian :one
SELECT s.id AS student_id, g.id AS guardian_id
FROM students s
JOIN guardians g ON g.student_id = s.id AND g.is_primary_contact
WHERE s.id = $1 AND s.school_id = $2 AND s.is_active
`

type GetStudentWithPrimaryGuardianParams struct {
	ID       pgtype.UUID `json:"id"`
	SchoolID pgtype.UUID `json:"school_id"`
}

type GetStudentWithPrimaryGuardianRow struct {
	StudentID  pgtype.UUID `json:"student_id"`
	GuardianID pgtype.UUID `json:"guardian_id"`
}

// Used when minting a PTM booking token: confirms the student is active
// in this school and finds the guardian the token is issued to.
func (q *Queries) GetStudentWithPrimaryGuardian(ctx context.Context, arg GetStudentWithPrimaryGuardianParams) (GetStudentWithPrimaryGuardianRow, error) {
	row := q.db.QueryRow(ctx, getStudentWithPrimaryGuardian, arg.ID, arg.SchoolID)
	var i GetStudentWithPrimaryGuardianRow
	err := row.Scan(&i.StudentID, &i.GuardianID)
	return i, err
}

const listWhatsappMessages = `-- name: ListWhatsappMessages :many
SELECT id, student_id, guardian_id, template, language, body_preview,
       status, sent_at, delivered_at, failure_reason, created_at
FROM whatsapp_messages
WHERE school_id = $1
  AND ($2::uuid IS NULL OR student_id = $2)
ORDER BY created_at DESC
LIMIT 100
`

type ListWhatsappMessagesParams struct {
	SchoolID  pgtype.UUID `json:"school_id"`
	StudentID pgtype.UUID `json:"student_id"`
}

type ListWhatsappMessagesRow struct {
	ID            pgtype.UUID        `json:"id"`
	StudentID     pgtype.UUID        `json:"student_id"`
	GuardianID    pgtype.UUID        `json:"guardian_id"`
	Template      string             `json:"template"`
	Language      string             `json:"language"`
	BodyPreview   *string            `json:"body_preview"`
	Status        string             `json:"status"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	FailureReason *string            `json:"failure_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListWhatsappMessages(ctx context.Context, arg ListWhatsappMessagesParams) ([]ListWhatsappMessagesRow, error) {
	rows, err := q.db.Query(ctx, listWhatsappMessages, arg.SchoolID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWhatsappMessagesRow
	for rows.Next() {
		var i ListWhatsappMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.GuardianID,
			&i.Template,
			&i.Language,
			&i.BodyPreview,
			&i.Status,
			&i.SentAt,
			&i.DeliveredAt,
			&i.FailureReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWhatsappMessageStatusTx = `-- name: UpdateWhatsappMessageStatusTx :one
UPDATE whatsapp_messages
SET status = $2
WHERE id = $1
RETURNING id
`

type UpdateWhatsappMessageStatusTxParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// RLS-scoped variant of the webhook's SECURITY DEFINER updater, for any
// future in-app status corrections. (The WATI webhook itself uses
// update_whatsapp_message_status — see migration 000014.)
func (q *Queries) UpdateWhatsappMessageStatusTx(ctx context.Context, arg UpdateWhatsappMessageStatusTxParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateWhatsappMessageStatusTx, arg.ID, arg.Status)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
