// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fees.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeeStructure = `-- name: CreateFeeStructure :one
INSERT INTO fee_structures (school_id, academic_year_id, class_id, component, amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, school_id, academic_year_id, class_id, component, amount, created_at
`

type CreateFeeStructureParams struct {
	SchoolID       pgtype.UUID    `json:"school_id"`
	AcademicYearID pgtype.UUID    `json:"academic_year_id"`
	ClassID        pgtype.UUID    `json:"class_id"`
	Component      string         `json:"component"`
	Amount         pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateFeeStructure(ctx context.Context, arg CreateFeeStructureParams) (FeeStructure, error) {
	row := q.db.QueryRow(ctx, createFeeStructure,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.ClassID,
		arg.Component,
		arg.Amount,
	)
	var i FeeStructure
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.Component,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaulters = `-- name: GetDefaulters :many
WITH due AS (
    SELECT s.id AS student_id, s.full_name, SUM(fs.amount) AS total_due
    FROM students s
    JOIN sections sec ON sec.id = s.section_id
    JOIN fee_structures fs ON fs.class_id = sec.class_id AND fs.academic_year_id = $2
    WHERE s.school_id = $1 AND s.is_active
    GROUP BY s.id, s.full_name
), paid AS (
    SELECT student_id, SUM(amount) AS total_paid
    FROM fee_payments
    WHERE academic_year_id = $2
    GROUP BY student_id
)
SELECT
    d.student_id,
    d.full_name,
    d.total_due::numeric AS total_due,
    COALESCE(p.total_paid, 0)::numeric AS total_paid,
    (d.total_due - COALESCE(p.total_paid, 0))::numeric AS balance_due,
    (SELECT MAX(fp.payment_date) FROM fee_payments fp
     WHERE fp.student_id = d.student_id AND fp.academic_year_id = $2)::date AS last_payment_date
FROM due d
LEFT JOIN paid p ON p.student_id = d.student_id
WHERE d.total_due - COALESCE(p.total_paid, 0) > 0
ORDER BY balance_due DESC
`

type GetDefaultersParams struct {
	SchoolID       pgtype.UUID `json:"school_id"`
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
}

type GetDefaultersRow struct {
	StudentID       pgtype.UUID    `json:"student_id"`
	FullName        string         `json:"full_name"`
	TotalDue        pgtype.Numeric `json:"total_due"`
	TotalPaid       pgtype.Numeric `json:"total_paid"`
	BalanceDue      pgtype.Numeric `json:"balance_due"`
	LastPaymentDate pgtype.Date    `json:"last_payment_date"`
}

// Students with a positive computed balance. last_payment_date stands in
// for "days overdue" — the schema has no per-component due dates yet
// (flagged as an open product question), so true overdue-ness is not
// computable.
func (q *Queries) GetDefaulters(ctx context.Context, arg GetDefaultersParams) ([]GetDefaultersRow, error) {
	rows, err := q.db.Query(ctx, getDefaulters, arg.SchoolID, arg.AcademicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDefaultersRow
	for rows.Next() {
		var i GetDefaultersRow
		if err := rows.Scan(
			&i.StudentID,
			&i.FullName,
			&i.TotalDue,
			&i.TotalPaid,
			&i.BalanceDue,
			&i.LastPaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeeStructures = `-- name: GetFeeStructures :many
SELECT id, school_id, academic_year_id, class_id, component, amount, created_at FROM fee_structures
WHERE class_id = $1 AND academic_year_id = $2
ORDER BY component
`

type GetFeeStructuresParams struct {
	ClassID        pgtype.UUID `json:"class_id"`
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
}

func (q *Queries) GetFeeStructures(ctx context.Context, arg GetFeeStructuresParams) ([]FeeStructure, error) {
	rows, err := q.db.Query(ctx, getFeeStructures, arg.ClassID, arg.AcademicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeeStructure
	for rows.Next() {
		var i FeeStructure
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.ClassID,
			&i.Component,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimaryGuardian = `-- name: GetPrimaryGuardian :one
SELECT id, language_pref FROM guardians
WHERE student_id = $1 AND is_primary_contact
LIMIT 1
`

type GetPrimaryGuardianRow struct {
	ID           pgtype.UUID `json:"id"`
	LanguagePref string      `json:"language_pref"`
}

func (q *Queries) GetPrimaryGuardian(ctx context.Context, studentID pgtype.UUID) (GetPrimaryGuardianRow, error) {
	row := q.db.QueryRow(ctx, getPrimaryGuardian, studentID)
	var i GetPrimaryGuardianRow
	err := row.Scan(&i.ID, &i.LanguagePref)
	return i, err
}

const getStudentFeeBalance = `-- name: GetStudentFeeBalance :one
SELECT
    COALESCE((
        SELECT SUM(fs.amount)
        FROM fee_structures fs
        JOIN sections sec ON sec.class_id = fs.class_id
        JOIN students st ON st.section_id = sec.id
        WHERE st.id = $1 AND fs.academic_year_id = $2
    ), 0)::numeric AS total_due,
    COALESCE((
        SELECT SUM(fp.amount)
        FROM fee_payments fp
        WHERE fp.student_id = $1 AND fp.academic_year_id = $2
    ), 0)::numeric AS total_paid
`

type GetStudentFeeBalanceParams struct {
	ID             pgtype.UUID `json:"id"`
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
}

type GetStudentFeeBalanceRow struct {
	TotalDue  pgtype.Numeric `json:"total_due"`
	TotalPaid pgtype.Numeric `json:"total_paid"`
}

// Balance is always computed, never stored (F-04): total due from the
// student's class fee structure minus total paid this academic year.
func (q *Queries) GetStudentFeeBalance(ctx context.Context, arg GetStudentFeeBalanceParams) (GetStudentFeeBalanceRow, error) {
	row := q.db.QueryRow(ctx, getStudentFeeBalance, arg.ID, arg.AcademicYearID)
	var i GetStudentFeeBalanceRow
	err := row.Scan(&i.TotalDue, &i.TotalPaid)
	return i, err
}

const hasRecentFeeReminder = `-- name: HasRecentFeeReminder :one
SELECT EXISTS (
    SELECT 1 FROM fee_reminders_log
    WHERE student_id = $1 AND sent_at > now() - interval '7 days'
)
`

// F-04 rate limit: 1 reminder per student per 7 days.
func (q *Queries) HasRecentFeeReminder(ctx context.Context, studentID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasRecentFeeReminder, studentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertFeeReminderLog = `-- name: InsertFeeReminderLog :exec
INSERT INTO fee_reminders_log (school_id, student_id, whatsapp_message_id)
VALUES ($1, $2, $3)
`

type InsertFeeReminderLogParams struct {
	SchoolID          pgtype.UUID `json:"school_id"`
	StudentID         pgtype.UUID `json:"student_id"`
	WhatsappMessageID pgtype.UUID `json:"whatsapp_message_id"`
}

func (q *Queries) InsertFeeReminderLog(ctx context.Context, arg InsertFeeReminderLogParams) error {
	_, err := q.db.Exec(ctx, insertFeeReminderLog, arg.SchoolID, arg.StudentID, arg.WhatsappMessageID)
	return err
}

const insertWhatsappMessage = `-- name: InsertWhatsappMessage :one
INSERT INTO whatsapp_messages (school_id, student_id, guardian_id, template, language, body_preview, status)
VALUES ($1, $2, $3, $4, $5, $6, 'queued')
RETURNING id
`

type InsertWhatsappMessageParams struct {
	SchoolID    pgtype.UUID `json:"school_id"`
	StudentID   pgtype.UUID `json:"student_id"`
	GuardianID  pgtype.UUID `json:"guardian_id"`
	Template    string      `json:"template"`
	Language    string      `json:"language"`
	BodyPreview *string     `json:"body_preview"`
}

// Rows start 'queued'; internal/jobs (the WATI dispatcher) owns the
// transition to sent/delivered/failed.
func (q *Queries) InsertWhatsappMessage(ctx context.Context, arg InsertWhatsappMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertWhatsappMessage,
		arg.SchoolID,
		arg.StudentID,
		arg.GuardianID,
		arg.Template,
		arg.Language,
		arg.BodyPreview,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const recordFeePayment = `-- name: RecordFeePayment :one
INSERT INTO fee_payments (school_id, student_id, academic_year_id, amount, payment_mode, payment_date, recorded_by, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, school_id, student_id, academic_year_id, amount, payment_mode, payment_date, recorded_by, note, created_at
`

type RecordFeePaymentParams struct {
	SchoolID       pgtype.UUID    `json:"school_id"`
	StudentID      pgtype.UUID    `json:"student_id"`
	AcademicYearID pgtype.UUID    `json:"academic_year_id"`
	Amount         pgtype.Numeric `json:"amount"`
	PaymentMode    string         `json:"payment_mode"`
	PaymentDate    pgtype.Date    `json:"payment_date"`
	RecordedBy     pgtype.UUID    `json:"recorded_by"`
	Note           *string        `json:"note"`
}

func (q *Queries) RecordFeePayment(ctx context.Context, arg RecordFeePaymentParams) (FeePayment, error) {
	row := q.db.QueryRow(ctx, recordFeePayment,
		arg.SchoolID,
		arg.StudentID,
		arg.AcademicYearID,
		arg.Amount,
		arg.PaymentMode,
		arg.PaymentDate,
		arg.RecordedBy,
		arg.Note,
	)
	var i FeePayment
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.StudentID,
		&i.AcademicYearID,
		&i.Amount,
		&i.PaymentMode,
		&i.PaymentDate,
		&i.RecordedBy,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
