// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicYear struct {
	ID        pgtype.UUID        `json:"id"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	Label     string             `json:"label"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	IsCurrent bool               `json:"is_current"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AiGeneration struct {
	ID             pgtype.UUID        `json:"id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	TeacherID      pgtype.UUID        `json:"teacher_id"`
	Feature        string             `json:"feature"`
	PromptVersion  string             `json:"prompt_version"`
	InputHash      string             `json:"input_hash"`
	InputJson      []byte             `json:"input_json"`
	OutputJson     []byte             `json:"output_json"`
	Language       string             `json:"language"`
	Model          string             `json:"model"`
	CostInr        pgtype.Numeric     `json:"cost_inr"`
	GeneratedAt    pgtype.Timestamptz `json:"generated_at"`
	CacheExpiresAt pgtype.Timestamptz `json:"cache_expires_at"`
}

type AiUsageQuotum struct {
	ID               pgtype.UUID `json:"id"`
	SchoolID         pgtype.UUID `json:"school_id"`
	AcademicYearID   pgtype.UUID `json:"academic_year_id"`
	Month            pgtype.Date `json:"month"`
	GenerationsUsed  int32       `json:"generations_used"`
	GenerationsLimit int32       `json:"generations_limit"`
}

type AttendanceRecord struct {
	ID        pgtype.UUID        `json:"id"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	StudentID pgtype.UUID        `json:"student_id"`
	SectionID pgtype.UUID        `json:"section_id"`
	Date      pgtype.Date        `json:"date"`
	Status    string             `json:"status"`
	MarkedBy  pgtype.UUID        `json:"marked_by"`
	MarkedAt  pgtype.Timestamptz `json:"marked_at"`
	EditedAt  pgtype.Timestamptz `json:"edited_at"`
	EditedBy  pgtype.UUID        `json:"edited_by"`
}

type AuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Action    string             `json:"action"`
	TableName string             `json:"table_name"`
	RecordID  pgtype.UUID        `json:"record_id"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Class struct {
	ID        pgtype.UUID        `json:"id"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	Name      string             `json:"name"`
	Board     *string            `json:"board"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ClassSubject struct {
	ID        pgtype.UUID `json:"id"`
	SchoolID  pgtype.UUID `json:"school_id"`
	ClassID   pgtype.UUID `json:"class_id"`
	SubjectID pgtype.UUID `json:"subject_id"`
}

type FeePayment struct {
	ID             pgtype.UUID        `json:"id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	AcademicYearID pgtype.UUID        `json:"academic_year_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	PaymentMode    string             `json:"payment_mode"`
	PaymentDate    pgtype.Date        `json:"payment_date"`
	RecordedBy     pgtype.UUID        `json:"recorded_by"`
	Note           *string            `json:"note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type FeeRemindersLog struct {
	ID                pgtype.UUID        `json:"id"`
	SchoolID          pgtype.UUID        `json:"school_id"`
	StudentID         pgtype.UUID        `json:"student_id"`
	WhatsappMessageID pgtype.UUID        `json:"whatsapp_message_id"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
}

type FeeStructure struct {
	ID             pgtype.UUID        `json:"id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	AcademicYearID pgtype.UUID        `json:"academic_year_id"`
	ClassID        pgtype.UUID        `json:"class_id"`
	Component      string             `json:"component"`
	Amount         pgtype.Numeric     `json:"amount"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Guardian struct {
	ID               pgtype.UUID        `json:"id"`
	SchoolID         pgtype.UUID        `json:"school_id"`
	StudentID        pgtype.UUID        `json:"student_id"`
	FullName         string             `json:"full_name"`
	Relation         *string            `json:"relation"`
	Phone            string             `json:"phone"`
	PhoneVerified    bool               `json:"phone_verified"`
	LanguagePref     string             `json:"language_pref"`
	IsPrimaryContact bool               `json:"is_primary_contact"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PtmBooking struct {
	ID           pgtype.UUID        `json:"id"`
	SchoolID     pgtype.UUID        `json:"school_id"`
	PtmSlotID    pgtype.UUID        `json:"ptm_slot_id"`
	StudentID    pgtype.UUID        `json:"student_id"`
	GuardianID   pgtype.UUID        `json:"guardian_id"`
	BookedAt     pgtype.Timestamptz `json:"booked_at"`
	ReminderSent bool               `json:"reminder_sent"`
}

type PtmSlot struct {
	ID        pgtype.UUID        `json:"id"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	SlotTime  pgtype.Timestamptz `json:"slot_time"`
	IsBooked  bool               `json:"is_booked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type School struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Slug               string             `json:"slug"`
	Board              string             `json:"board"`
	City               *string            `json:"city"`
	State              *string            `json:"state"`
	Phone              *string            `json:"phone"`
	SubscriptionTier   string             `json:"subscription_tier"`
	SubscriptionStatus string             `json:"subscription_status"`
	PilotStartedAt     pgtype.Timestamptz `json:"pilot_started_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Section struct {
	ID             pgtype.UUID        `json:"id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	ClassID        pgtype.UUID        `json:"class_id"`
	Name           string             `json:"name"`
	ClassTeacherID pgtype.UUID        `json:"class_teacher_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Student struct {
	ID              pgtype.UUID        `json:"id"`
	SchoolID        pgtype.UUID        `json:"school_id"`
	SectionID       pgtype.UUID        `json:"section_id"`
	AdmissionNumber string             `json:"admission_number"`
	FullName        string             `json:"full_name"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	Gender          *string            `json:"gender"`
	IsActive        bool               `json:"is_active"`
	WithdrawnAt     pgtype.Timestamptz `json:"withdrawn_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Subject struct {
	ID        pgtype.UUID        `json:"id"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Substitution struct {
	ID                  pgtype.UUID        `json:"id"`
	SchoolID            pgtype.UUID        `json:"school_id"`
	TimetableSlotID     pgtype.UUID        `json:"timetable_slot_id"`
	Date                pgtype.Date        `json:"date"`
	AbsentTeacherID     pgtype.UUID        `json:"absent_teacher_id"`
	SubstituteTeacherID pgtype.UUID        `json:"substitute_teacher_id"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type TeacherAssignment struct {
	ID             pgtype.UUID        `json:"id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	TeacherID      pgtype.UUID        `json:"teacher_id"`
	SectionID      pgtype.UUID        `json:"section_id"`
	SubjectID      pgtype.UUID        `json:"subject_id"`
	AcademicYearID pgtype.UUID        `json:"academic_year_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TimetableSlot struct {
	ID             pgtype.UUID `json:"id"`
	SchoolID       pgtype.UUID `json:"school_id"`
	SectionID      pgtype.UUID `json:"section_id"`
	SubjectID      pgtype.UUID `json:"subject_id"`
	TeacherID      pgtype.UUID `json:"teacher_id"`
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
	DayOfWeek      int32       `json:"day_of_week"`
	PeriodNumber   int32       `json:"period_number"`
}

type UserProfile struct {
	ID           pgtype.UUID        `json:"id"`
	SchoolID     pgtype.UUID        `json:"school_id"`
	Role         string             `json:"role"`
	FullName     string             `json:"full_name"`
	Phone        string             `json:"phone"`
	LanguagePref string             `json:"language_pref"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WhatsappMessage struct {
	ID            pgtype.UUID        `json:"id"`
	SchoolID      pgtype.UUID        `json:"school_id"`
	StudentID     pgtype.UUID        `json:"student_id"`
	GuardianID    pgtype.UUID        `json:"guardian_id"`
	Template      string             `json:"template"`
	Language      string             `json:"language"`
	BodyPreview   *string            `json:"body_preview"`
	Status        string             `json:"status"`
	WatiMessageID *string            `json:"wati_message_id"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	FailureReason *string            `json:"failure_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
